project:
  type: book

book:
  favicon: images/apple-touch-icon.png
  title: "rOpenSci Translation Guidelines"
  author: "Yanina Bellini Saibene, Maëlle Salmon, Paola Corrales, Elio Campiteli"
#  code-link: true
  description: |
    Why and how we localize and translate our material.
  reader-mode: true
  site-url: https://translationguide.ropensci.org/
  repo-url: https://github.com/ropensci-review-tools/translation_guide/
  repo-actions: [edit, issue]

  chapters:
  - index.Rmd
  - motivation.Rmd
  - intro.Rmd
  - howtoreview.Rmd
  - specific_guidelines.Rmd
  - booknews.Rmd

format:
  html:
    theme: [cosmo, custom.scss]
    code-link: true
    include-in-header: "matomo.html"
  pdf:
    output-file: "translation_guide"

babelquarto:
  mainlanguage: 'en'
  languages: ['es']
title-es: Guía de traducción de rOpenSci
description-es: description in es
lang: en
