on:
  pull_request:
    branches: [main, master]

name: PR-workflow

jobs:
  bookdown:
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
    name: Render Book
    runs-on: ubuntu-latest
    if: github.repository == 'ropensci-review-tools/translation_guide'
    steps:
      - name: Is this a fork
        run: |
          fork=$(jq --raw-output .pull_request.head.repo.fork "${GITHUB_EVENT_PATH}");echo "fork=${fork}" >> $GITHUB_ENV

      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: quarto-dev/quarto-actions/setup@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-tinytex@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: local::.

      - name: Render book
        run: Rscript -e 'babelquarto::render_book()'

      - name: Move English files
        run: Rscript -e 'file.copy(from = "_book/rOpenSci-Translation-Guidelines.pdf", to = "_book/ropensci-translation-guide.pdf")' -e 'purrr::walk(list.files("images", full.names = TRUE), file.copy, to = "_book/images")'

      - name: Move Spanish files
        run: Rscript -e 'file.copy(from = "_book/es/Guía-de-traducción-de-rOpenSci.pdf", to = "_book/es/ropensci-translation-guide.pdf")' -e 'purrr::walk(list.files("images", full.names = TRUE), file.copy, to = "_book/es/images")'

      - name: git config
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "gh-pages committer"
      - name: Deploy to Netlify
        id: netlify-deploy
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './_book'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message:
            'Deploy from GHA: ${{ github.event.pull_request.title || github.event.head_commit.message }} (${{ github.sha }})'
          # these all default to 'true'
          enable-pull-request-comment: false
          enable-commit-comment: false
          # enable-commit-status: true
          #o verwrites-pull-request-comment: true
        timeout-minutes: 1
